// Form fields
export const EMAIL_FIELD_ID = 'emailField'
export const BILLING_ADDRESS_NAME_FIELD_ID = 'billingAddressNameField'
export const BILLING_ADDRESS_LINE1_FIELD_ID = 'billingAddressLine1Field'
export const BILLING_ADDRESS_ZIP_FIELD_ID = 'billingAddressZipField'
export const BILLING_ADDRESS_CITY_FIELD_ID = 'billingAddressCityField'
export const BILLING_ADDRESS_COUNTRY_FIELD_ID = 'billingAddressCountryField'
export const SHIPPING_ADDRESS_NAME_FIELD_ID = 'shippingAddressNameField'
export const SHIPPING_ADDRESS_LINE1_FIELD_ID = 'shippingAddressLine1Field'
export const SHIPPING_ADDRESS_ZIP_FIELD_ID = 'shippingAddressZipField'
export const SHIPPING_ADDRESS_CITY_FIELD_ID = 'shippingAddressCityField'
export const SHIPPING_ADDRESS_COUNTRY_FIELD_ID = 'shippingAddressCountryField'
export const PHONE_FIELD_ID = 'phoneField'
export const OUTCOME_MESSAGE_ID = 'outcomeMessage'
