// Global
export const PAGE_LOADING_ID = 'zcoPageLoading'
export const STRIPE_CARD_ID = 'zcoStripeCard'

// Checkout
export const EMAIL_FIELD_ID = 'zcoEmailField'
export const BILLING_ADDRESS_NAME_FIELD_ID = 'zcoBillingAddressNameField'
export const BILLING_ADDRESS_LINE1_FIELD_ID = 'zcoBillingAddressLine1Field'
export const BILLING_ADDRESS_ZIP_FIELD_ID = 'zcoBillingAddressZipField'
export const BILLING_ADDRESS_CITY_FIELD_ID = 'zcoBillingAddressCityField'
export const BILLING_ADDRESS_STATE_FIELD_ID = 'zcoBillingAddressStateField'
export const BILLING_ADDRESS_COUNTRY_FIELD_ID = 'zcoBillingAddressCountryField'
export const SHIPPING_ADDRESS_NAME_FIELD_ID = 'zcoShippingAddressNameField'
export const SHIPPING_ADDRESS_LINE1_FIELD_ID = 'zcoShippingAddressLine1Field'
export const SHIPPING_ADDRESS_ZIP_FIELD_ID = 'zcoShippingAddressZipField'
export const SHIPPING_ADDRESS_CITY_FIELD_ID = 'zcoShippingAddressCityField'
export const SHIPPING_ADDRESS_STATE_FIELD_ID = 'zcoShippingAddressStateField'
export const SHIPPING_ADDRESS_COUNTRY_FIELD_ID = 'zcoShippingAddressCountryField'
export const PHONE_FIELD_ID = 'zcoPhoneField'
export const OUTCOME_MESSAGE_ID = 'zcoOutcomeMessage'
export const SAME_SHIPPING_BILLING_CHECKBOX_ID = 'zcoSameBillingShippingCheckbox'
export const ADDRESS_TOGGLE_ID = 'zcoAddressToggle'
export const SHIPPING_METHOD_ID = 'zcoShippingMethod'
export const PAYMENT_METHOD_FIELD_ID = 'zcoPaymentMethod'
export const PAYMENT_TERM_FIELD_ID = 'zcoPaymentTerm'
export const PAY_BUTTON_ID = 'zcoPayButton'
export const SALES_TAX_ID = 'zcoSalesTax' // NOTE: This is technically not formData, but included for convenience

// Test cases
export const CURRENT_TEST_CASE_ID = 'zcoCurrentTestCase'
export const CURRENT_TEST_CASE_READY_ID = 'zcoCurrentTestCaseReady'
export const CURRENT_TEST_CASE_COUNTRY_CODE_ID = 'zcoCurrentTestCaseCountryCode'
export const CURRENT_TEST_CASE_LOCALE_ID = 'zcoCurrentTestCaseLocale'
export const CURRENT_TEST_CASE_CUSTOMER_ID = 'zcoCurrentTestCaseCustomer'
export const CURRENT_TEST_CASE_EXPECTED_ID = 'zcoCurrentTestCaseExpected'
